server:
  port: 7051
eureka:
  instance:
    hostname: netflix1
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:7052/eureka/,http://localhost:7053/eureka/
    register-with-eureka: false
    fetch-registry: false
